[package]
name = "dftx-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dftx-macro = { path = "../dftx-macro" }
anyhow = "1.0.75"
bitcoin = "0.31.0"
hex = "0.4.3"
bitflags = "2.4.1"

